# Generated by Django 2.2.7 on 2021-02-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('dataCreate', models.DateTimeField()),
                ('categori', models.TextField()),
            ],
        ),
    ]
